package medicalgap.dao.entity;

// Generated 29 juin 2016 13:40:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;



/**
 * Congresses generated by hbm2java
 */
@Entity
@Table(name = "congresses", catalog = "medicalgap")
public class Congresses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8982320543838658241L;
	private Long idCongresses;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date date;
	private String auteur;
	private String titre;
	private String produit;
	private String impact;
	private String reference;
	private Long nbreTotalBc;
	private Long nbreTotal;
	private String compagny;
	private String type;
	private String categorie;
	private String conclusion;
	private String gapsInsightReco;
	private String frequence;
	private String responsable;

	public Congresses() {
	}

	public Congresses(String type, String categorie) {
		this.type = type;
		this.categorie = categorie;
	}
	
	public Congresses(Date date, String auteur, String titre, String produit,
			String impact, String reference, Long nbreTotalBc, Long nbreTotal,
			String compagny, String type, String categorie, String conclusion,
			String gapsInsightReco, String frequence, String responsable) {
		this.date = date;
		this.auteur = auteur;
		this.titre = titre;
		this.produit = produit;
		this.impact = impact;
		this.reference = reference;
		this.nbreTotalBc = nbreTotalBc;
		this.nbreTotal = nbreTotal;
		this.compagny = compagny;
		this.type = type;
		this.categorie = categorie;
		this.conclusion = conclusion;
		this.gapsInsightReco = gapsInsightReco;
		this.frequence = frequence;
		this.responsable = responsable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_congresses", unique = true, nullable = false)
	public Long getIdCongresses() {
		return this.idCongresses;
	}

	public void setIdCongresses(Long idCongresses) {
		this.idCongresses = idCongresses;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Auteur", length = 100)
	public String getAuteur() {
		return this.auteur;
	}

	public void setAuteur(String auteur) {
		this.auteur = auteur;
	}

	@Column(name = "Titre", length = 200)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "Produit", length = 300)
	public String getProduit() {
		return this.produit;
	}

	public void setProduit(String produit) {
		this.produit = produit;
	}

	@Column(name = "Impact", length = 300)
	public String getImpact() {
		return this.impact;
	}

	public void setImpact(String impact) {
		this.impact = impact;
	}

	@Column(name = "Reference", length = 300)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "Nbre_total_bc")
	public Long getNbreTotalBc() {
		return this.nbreTotalBc;
	}

	public void setNbreTotalBc(Long nbreTotalBc) {
		this.nbreTotalBc = nbreTotalBc;
	}

	@Column(name = "Nbre_total")
	public Long getNbreTotal() {
		return this.nbreTotal;
	}

	public void setNbreTotal(Long nbreTotal) {
		this.nbreTotal = nbreTotal;
	}

	@Column(name = "Compagny", length = 200)
	public String getCompagny() {
		return this.compagny;
	}

	public void setCompagny(String compagny) {
		this.compagny = compagny;
	}

	@Column(name = "Type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Categorie", length = 50)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Column(name = "Conclusion", length = 300)
	public String getConclusion() {
		return this.conclusion;
	}

	public void setConclusion(String conclusion) {
		this.conclusion = conclusion;
	}

	@Column(name = "Gaps_Insight_Reco", length = 300)
	public String getGapsInsightReco() {
		return this.gapsInsightReco;
	}

	public void setGapsInsightReco(String gapsInsightReco) {
		this.gapsInsightReco = gapsInsightReco;
	}

	@Column(name = "Frequence", length = 300)
	public String getFrequence() {
		return this.frequence;
	}

	public void setFrequence(String frequence) {
		this.frequence = frequence;
	}

	@Column(name = "Responsable", length = 300)
	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	@Override
	public String toString() {
		return "Congresses [idCongresses=" + idCongresses + ", date=" + date
				+ ", auteur=" + auteur + ", titre=" + titre + ", produit="
				+ produit + ", impact=" + impact + ", reference=" + reference
				+ ", nbreTotalBc=" + nbreTotalBc + ", nbreTotal=" + nbreTotal
				+ ", compagny=" + compagny + ", type=" + type + ", categorie="
				+ categorie + ", conclusion=" + conclusion
				+ ", gapsInsightReco=" + gapsInsightReco + ", frequence="
				+ frequence + ", responsable=" + responsable + "]";
	}

}
