package medicalgap.dao.entity;

// Generated 29 juin 2016 13:40:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * RegistresDesCancers generated by hbm2java
 */
@Entity
@Table(name = "registres_des_cancers", catalog = "medicalgap")
public class RegistresDesCancers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3126990093563115068L;
	private Long idRegistre;
	
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
	private Date date;
	private Float ageMedian;
	private Float nbrePopulation;
	private String incidence;
	private String stade;
	private String typeHisto;
	private String sourceLien;
	private String conclusion;
	private String gapsInsightReco;
	private String frequence;
	private String compagny;
	private String responsable;
	private String type;
	private String ville;
	private String categorie;

	public RegistresDesCancers() {
	}
	
	public RegistresDesCancers(String type, String categorie) {
		
		this.type = type;
		this.categorie = categorie;
	}

	public RegistresDesCancers(Date date, Float ageMedian,
			Float nbrePopulation, String incidence, String stade,
			String typeHisto, String sourceLien, String conclusion,
			String gapsInsightReco, String frequence, String responsable,
			String type, String ville, String categorie,String compagny) {
		this.date = date;
		this.ageMedian = ageMedian;
		this.nbrePopulation = nbrePopulation;
		this.incidence = incidence;
		this.stade = stade;
		this.typeHisto = typeHisto;
		this.sourceLien = sourceLien;
		this.conclusion = conclusion;
		this.gapsInsightReco = gapsInsightReco;
		this.frequence = frequence;
		this.responsable = responsable;
		this.type = type;
		this.ville = ville;
		this.categorie = categorie;
		this.compagny = compagny;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_registre", unique = true)
	public Long getIdRegistre() {
		return this.idRegistre;
	}

	public void setIdRegistre(Long idRegistre) {
		this.idRegistre = idRegistre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Age_Median", precision = 12, scale = 0)
	public Float getAgeMedian() {
		return this.ageMedian;
	}

	public void setAgeMedian(Float ageMedian) {
		this.ageMedian = ageMedian;
	}

	@Column(name = "Nbre_Population", precision = 12, scale = 0)
	public Float getNbrePopulation() {
		return this.nbrePopulation;
	}

	public void setNbrePopulation(Float nbrePopulation) {
		this.nbrePopulation = nbrePopulation;
	}

	@Column(name = "Incidence", length = 50)
	public String getIncidence() {
		return this.incidence;
	}

	public void setIncidence(String incidence) {
		this.incidence = incidence;
	}

	@Column(name = "Stade", length = 100)
	public String getStade() {
		return this.stade;
	}

	public void setStade(String stade) {
		this.stade = stade;
	}

	@Column(name = "Type_Histo", length = 100)
	public String getTypeHisto() {
		return this.typeHisto;
	}

	public void setTypeHisto(String typeHisto) {
		this.typeHisto = typeHisto;
	}

	@Column(name = "Source_Lien", length = 100)
	public String getSourceLien() {
		return this.sourceLien;
	}

	public void setSourceLien(String sourceLien) {
		this.sourceLien = sourceLien;
	}

	@Column(name = "Conclusion", length = 500)
	public String getConclusion() {
		return this.conclusion;
	}

	public void setConclusion(String conclusion) {
		this.conclusion = conclusion;
	}

	@Column(name = "Gaps_Insight_Reco", length = 500)
	public String getGapsInsightReco() {
		return this.gapsInsightReco;
	}

	public void setGapsInsightReco(String gapsInsightReco) {
		this.gapsInsightReco = gapsInsightReco;
	}

	@Column(name = "Frequence", length = 100)
	public String getFrequence() {
		return this.frequence;
	}

	public void setFrequence(String frequence) {
		this.frequence = frequence;
	}

	@Column(name = "Responsable", length = 100)
	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	@Column(name = "Type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Ville", length = 100)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "Categorie", length = 100)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Override
	public String toString() {
		return "RegistresDesCancers [idRegistre=" + idRegistre + ", date="
				+ date + ", ageMedian=" + ageMedian + ", nbrePopulation="
				+ nbrePopulation + ", incidence=" + incidence + ", stade="
				+ stade + ", typeHisto=" + typeHisto + ", sourceLien="
				+ sourceLien + ", conclusion=" + conclusion
				+ ", gapsInsightReco=" + gapsInsightReco + ", frequence="
				+ frequence + ", responsable=" + responsable + ", type=" + type
				+ ", ville=" + ville + ", categorie=" + categorie + "]";
	}

	@Column(name = "Compagny", length = 200)
	public String getCompagny() {
		return this.compagny;
	}

	public void setCompagny(String compagny) {
		this.compagny = compagny;
	}
}
