package medicalgap.dao.entity;

// Generated 29 juin 2016 13:40:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Tae generated by hbm2java
 */
@Entity
@Table(name = "tae", catalog = "medicalgap")
public class Tae implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7161590668780502823L;
	private Long idTae;
	
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
	private Date date;
	private Float nbrePubBc;
	private Float nbreTot;
	private String titreHcp;
	private String essaiClinique;
	private String type;
	private String compagny;
	private String categorie;
	private String proprietaire;
	private String conclusion;
	private String gapsInsightReco;
	private String frequence;
	private String responsable;

	public Tae() {
	}

	public Tae(Date date, Float nbrePubBc, Float nbreTot, String titreHcp,
			String essaiClinique, String type, String categorie,
			String proprietaire, String conclusion, String gapsInsightReco,
			String frequence, String responsable, String compagny) {
		this.date = date;
		this.nbrePubBc = nbrePubBc;
		this.nbreTot = nbreTot;
		this.titreHcp = titreHcp;
		this.essaiClinique = essaiClinique;
		this.type = type;
		this.categorie = categorie;
		this.proprietaire = proprietaire;
		this.conclusion = conclusion;
		this.gapsInsightReco = gapsInsightReco;
		this.frequence = frequence;
		this.responsable = responsable;
		this.compagny = compagny;
	}

	public Tae(String type, String categorie) {
		
		this.type = type;
		this.categorie = categorie;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tae", unique = true, nullable = false)
	public Long getIdTae() {
		return this.idTae;
	}

	public void setIdTae(Long idTae) {
		this.idTae = idTae;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Nbre_pub_bc", precision = 12, scale = 0)
	public Float getNbrePubBc() {
		return this.nbrePubBc;
	}

	public void setNbrePubBc(Float nbrePubBc) {
		this.nbrePubBc = nbrePubBc;
	}

	@Column(name = "Nbre_tot", precision = 12, scale = 0)
	public Float getNbreTot() {
		return this.nbreTot;
	}

	public void setNbreTot(Float nbreTot) {
		this.nbreTot = nbreTot;
	}

	@Column(name = "Titre_hcp", length = 100)
	public String getTitreHcp() {
		return this.titreHcp;
	}

	public void setTitreHcp(String titreHcp) {
		this.titreHcp = titreHcp;
	}

	@Column(name = "Essai_clinique", length = 500)
	public String getEssaiClinique() {
		return this.essaiClinique;
	}

	public void setEssaiClinique(String essaiClinique) {
		this.essaiClinique = essaiClinique;
	}

	@Column(name = "Type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Categorie", length = 100)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Column(name = "Proprietaire", length = 50)
	public String getProprietaire() {
		return this.proprietaire;
	}

	public void setProprietaire(String proprietaire) {
		this.proprietaire = proprietaire;
	}

	@Column(name = "Conclusion", length = 300)
	public String getConclusion() {
		return this.conclusion;
	}

	public void setConclusion(String conclusion) {
		this.conclusion = conclusion;
	}

	@Column(name = "Gaps_Insight_Reco", length = 300)
	public String getGapsInsightReco() {
		return this.gapsInsightReco;
	}

	public void setGapsInsightReco(String gapsInsightReco) {
		this.gapsInsightReco = gapsInsightReco;
	}

	@Column(name = "Frequence", length = 300)
	public String getFrequence() {
		return this.frequence;
	}

	public void setFrequence(String frequence) {
		this.frequence = frequence;
	}

	@Column(name = "Responsable", length = 300)
	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	@Column(name = "Compagny", length = 200)
	public String getCompagny() {
		return this.compagny;
	}

	public void setCompagny(String compagny) {
		this.compagny = compagny;
	}
}
